name: Deployment

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Sign jar
      run: |
        echo "${{ secrets.KEYSTORE }}" > .keystore.asc
        gpg -d --passphrase ${{ secrets.PASSPHRASE }} --batch .keystore.asc > .keystore
        jarsigner \
        -keystore .keystore \
        -storepass ${{ secrets.STOREPASS }} \
        -keypass ${{ secrets.KEYPASS }} \
        target/${{ github.event.repository.name }}.jar \
        ${{ secrets.ALIAS }}
    - name: Update remote gist
      run: |
        cd ../
        git config --global user.email "cli@github.com"
        git config --global user.name "Github Actions"
        git clone --depth=1 https://gist.github.com/dd496e2dd48fb610ca4bccc3be1f59f3.git remote
        cp ${{ github.event.repository.name }}/target/${{ github.event.repository.name }}.jar remote/
        cd remote
        git add .
        git commit -m "Testing"
        git push https://github.com/kekawce:${{ secrets.API_TOKEN_GITHUB }}@gist.github.com/dd496e2dd48fb610ca4bccc3be1f59f3.git

        

        
        
