name: Deployment

on:
  push:
    branches: master
    tags: v[0-9]*

jobs:
  deploy:
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      JAR_NAME: ${{ github.event.repository.name }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Sign jar
      run: |
        echo "${{ secrets.KEYSTORE }}" > .keystore.asc
        gpg -d --passphrase ${{ secrets.PASSPHRASE }} --batch .keystore.asc > .keystore
        jarsigner \
        -keystore .keystore \
        -storepass ${{ secrets.STOREPASS }} \
        -keypass ${{ secrets.KEYPASS }} \
        target/${JAR_NAME}.jar \
        ${{ secrets.ALIAS }}
    - name: Update version and push
      run: |
        cd src/main/resources/
        tmp=$(mktemp)
        echo ::set-env name=TAG::${GITHUB_REF#refs/*/}
        ver="$TAG"
        ver=$(echo "$ver" | tr '-' ' ')
        ver="${ver:1}"
        echo ::set-env name=VER::$ver
        jq --arg v "$ver" '.version = $v' plugin.json > "$tmp"
        mv "$tmp" plugin.json
        git config --global user.email "cli@github.com"
        git config --global user.name "Github Actions"
        git commit -am "Update to v${ver}"
        git tag -f -a $TAG
        git push -f --tags
    - name: Update and push to remote gist
      env:
        GIST_LINK: "gist.github.com/dd496e2dd48fb610ca4bccc3be1f59f3.git"
      run: |
        cd ../
        git clone --depth=1 https://$GIST_LINK remote
        cp ${REPO_NAME}/target/${JAR_NAME}.jar remote/
        cp ${REPO_NAME}/src/main/resources/plugin.json remote/
        cd remote
        git commit -am "Update to v${VER}"
        git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@$GIST_LINK

        
        
