# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Sign jar
      run: |
        echo "${{ secrets.KEYSTORE }}" > .keystore.asc
        gpg -d --passphrase ${{ secrets.PASSPHRASE }} --batch .keystore.asc > .keystore
        jarsigner \
        -keystore .keystore \
        -storepass ${{ secrets.STOREPASS }} \
        -keypass ${{ secrets.KEYPASS }} \
        target/${{ github.event.repository.name }}.jar \
        ${{ secrets.ALIAS }}
    - name: Update remote gist
      run: |
        cd ../
        git config --global user.email "cli@github.com"
        git config --global user.name "Github Actions"
        git clone --depth=1 https://gist.github.com/kekawce/dd496e2dd48fb610ca4bccc3be1f59f3 remote
        stat remote/${{ github.event.repository.name }}.jar
        cp KEKW/target/${{ github.event.repository.name }}.jar remote/
        cd remote
        stat ${{ github.event.repository.name }}.jar
        

        
        
