name: test

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo "this is v$RELEASE_VERSION"
          echo "this is v${{ env.RELEASE_VERSION }}"
          echo "$RELEASE_VERSION"
          echo "${{ env.RELEASE_VERSION }}"


        

        
        
