name: test

on:
  workflow_dispatch

jobs:
  deploy:
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      JAR_NAME: ${{ github.event.repository.name }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
         cd src/main/resources/
         tmp=$(mktemp)
         ver="v1.9.9 beta 21"
         jq --arg v "$ver" '.version = $v' plugin.json > "$tmp"
         rm "$tmp"
         cat plugin.json


        

        
        
