name: test

on:
  workflow_dispatch

jobs:
  deploy:
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      JAR_NAME: ${{ github.event.repository.name }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: echo "${GITHUB_REF}"


        

        
        
