# .github/workflows/test.yml
name: test

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: test
        run: |
          cd src/main/resources
          version=$(jq .version plugin.json)
          echo $version
          



        

        
        
