name: test

on:
  workflow_dispatch

jobs:
  deploy:
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      JAR_NAME: ${{ github.event.repository.name }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        ver=$TAG
        echo "$ver"
        ver=$(echo "$ver" | tr '-' ' ')
        ver="${ver:1}"
        echo "$ver"
        echo "${{ env.TAG }}"
        echo $TAG
        echo "VER=$ver" >> $GITHUB_ENV
        echo $VER



        

        
        
